const HTTP_OK_STATUS = 200;
const HTTP_CREATED = 201;
const HTTP_SERVER_ERROR = 500;
const HTTP_NOT_FOUND = 404;
const HTTP_CLIENT_ERROR = 400;
const HTTP_UNAUTHORIZED = 401;

module.exports = {
  HTTP_NOT_FOUND,
  HTTP_OK_STATUS,
  HTTP_SERVER_ERROR,
  HTTP_CLIENT_ERROR,
  HTTP_UNAUTHORIZED,
  HTTP_CREATED,
};
